# Alexa Prompts Language Constants

SKILL_NAME = "SKILL_NAME"
GET_PROMPT_MESSAGE = "GET_PROMPT_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
PROMPTS = "PROMPTS"
RESTAURANT_PROMPTS = "RESTAURANT_PROMPTS"
AIRPORT_PROMPTS = "AIRPORT_PROMPTS"
TRAIN_PROMPTS = "TRAIN_PROMPTS"